### ISSUE TITLE
训练yolox-s出现RuntimeError: CUDA error: device-side assert triggered问题

### ISSUE THREAD

**Issue by GuoXu-booo** [Megvii-BaseDetection/YOLOX#1161]
尝试减少batch和input_size,没有效果，之前可以正常训练，现在报错：
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [10,0,0], thread: [26,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [10,0,0], thread: [27,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [10,0,0], thread: [28,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [10,0,0], thread: [29,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [10,0,0], thread: [30,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [10,0,0], thread: [31,0,0] Assertion `input_val >= zero && input_val <= one` failed.
2022-03-03 14:35:41 | ERROR    | yolox.models.yolo_head:328 - OOM RuntimeError is raised due to the huge memory cost during label assignment.                            CPU mode is applied in this batch. If you want to avoid this issue,                            try to reduce the batch size or image size.
2022-03-03 14:35:41 | INFO     | yolox.core.trainer:196 - Training of experiment is done and the best AP is 0.00
2022-03-03 14:35:41 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (32), thread 'MainThread' (140133772625728):
Traceback (most recent call last):

  File "/project/train/src_repo/YOLOX/tools/../yolox/models/yolo_head.py", line 322, in get_losses
    imgs,
    └ <unprintable Tensor object>

  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ <unprintable tuple object>
           └ <function YOLOXHead.get_assignments at 0x7f731c7157b8>

  File "/project/train/src_repo/YOLOX/tools/../yolox/models/yolo_head.py", line 505, in get_assignments
    ) = self.dynamic_k_matching(cost, pair_wise_ious, gt_classes, num_gt, fg_mask)
        │    │                  │     │               │           │       └ <unprintable Tensor object>
        │    │                  │     │               │           └ 2
        │    │                  │     │               └ <unprintable Tensor object>
        │    │                  │     └ <unprintable Tensor object>
        │    │                  └ <unprintable Tensor object>
        │    └ <function YOLOXHead.dynamic_k_matching at 0x7f731c715950>
        └ YOLOXHead(
            (cls_convs): ModuleList(
              (0): Sequential(
                (0): BaseConv(
                  (conv): Conv2d(128, 128, kernel_size=...

  File "/project/train/src_repo/YOLOX/tools/../yolox/models/yolo_head.py", line 616, in dynamic_k_matching
    dynamic_ks = dynamic_ks.tolist()
                 │          └ <method 'tolist' of 'torch._C._TensorBase' objects>
                 └ <unprintable Tensor object>

RuntimeError: CUDA error: device-side assert triggered

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "train.py", line 146, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=8, cache=False, ckpt='/project/train/models/weight/yolox_s.pth', devices=0, dist_backend='nccl', dist_ur...
          └ ╒═══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...

> File "/project/train/src_repo/YOLOX/tools/../yolox/core/launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒═══════════════════╤═══════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7f731c747ae8>

  File "train.py", line 124, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7f72d48b2bf8>
    └ <yolox.core.trainer.Trainer object at 0x7f731c7589e8>

  File "/project/train/src_repo/YOLOX/tools/../yolox/core/trainer.py", line 74, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x7f72d48d3f28>
    └ <yolox.core.trainer.Trainer object at 0x7f731c7589e8>

  File "/project/train/src_repo/YOLOX/tools/../yolox/core/trainer.py", line 83, in train_in_epoch
    self.train_in_iter()
    │    └ <function Trainer.train_in_iter at 0x7f731c745950>
    └ <yolox.core.trainer.Trainer object at 0x7f731c7589e8>

  File "/project/train/src_repo/YOLOX/tools/../yolox/core/trainer.py", line 89, in train_in_iter
    self.train_one_iter()
    │    └ <function Trainer.train_one_iter at 0x7f731c7459d8>
    └ <yolox.core.trainer.Trainer object at 0x7f731c7589e8>

  File "/project/train/src_repo/YOLOX/tools/../yolox/core/trainer.py", line 103, in train_one_iter
    outputs = self.model(inps, targets)
              │    │     │     └ <unprintable Tensor object>
              │    │     └ <unprintable Tensor object>
              │    └ YOLOX(
              │        (backbone): YOLOPAFPN(
              │          (backbone): CSPDarknet(
              │            (stem): Focus(
              │              (conv): BaseConv(
              │                (conv): ...
              └ <yolox.core.trainer.Trainer object at 0x7f731c7589e8>

  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
             │    │        │        └ {}
             │    │        └ <unprintable tuple object>
             │    └ <function YOLOX.forward at 0x7f731c715c80>
             └ YOLOX(
                 (backbone): YOLOPAFPN(
                   (backbone): CSPDarknet(
                     (stem): Focus(
                       (conv): BaseConv(
                         (conv): ...

  File "/project/train/src_repo/YOLOX/tools/../yolox/models/yolox.py", line 35, in forward
    fpn_outs, targets, x
    │         │        └ <unprintable Tensor object>
    │         └ <unprintable Tensor object>
    └ <unprintable tuple object>

  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
             │    │        │        └ {}
             │    │        └ <unprintable tuple object>
             │    └ <function YOLOXHead.forward at 0x7f731c715510>
             └ YOLOXHead(
                 (cls_convs): ModuleList(
                   (0): Sequential(
                     (0): BaseConv(
                       (conv): Conv2d(128, 128, kernel_size=...

  File "/project/train/src_repo/YOLOX/tools/../yolox/models/yolo_head.py", line 203, in forward
    dtype=xin[0].dtype,
          └ <unprintable tuple object>

  File "/project/train/src_repo/YOLOX/tools/../yolox/models/yolo_head.py", line 352, in get_losses
    "cpu",

  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ <unprintable tuple object>
           └ <function YOLOXHead.get_assignments at 0x7f731c7157b8>

  File "/project/train/src_repo/YOLOX/tools/../yolox/models/yolo_head.py", line 446, in get_assignments
    gt_bboxes_per_image = gt_bboxes_per_image.cpu().float()
                          │                   └ <method 'cpu' of 'torch._C._TensorBase' objects>
                          └ <unprintable Tensor object>

RuntimeError: CUDA error: device-side assert triggered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered

**Comment by GuoXu-booo** [comment]
Why did this error occur55555

**Comment by wangyirui** [comment]
I have the same issue when training ByteTrack with YOLOX-X

**Comment by FateScript** [comment]
Did you modify any code?

**Comment by GuoXu-booo** [comment]
> Did you modify any code?

The code was not modified，I found the problem in reg_conv module through debug

**Comment by GuoXu-booo** [comment]
> Did you modify any code?

![image](https://user-images.githubusercontent.com/54988783/157159569-6ad8498f-ee21-4c2a-99fc-890ada589353.png)

**Comment by GuoXu-booo** [comment]
> Did you modify any code?

Is there something wrong with my graphics card？Or float16？It can still run on the server before。

**Comment by ELongking** [comment]
tesla v100, face the same problems even after trying to change batchsize, suddenly encountered it and there was no such error reported before, besides find the reg_feat as NaN tensor like the former one

**Comment by ilmoney** [comment]
> tesla v100, face the same problems even after trying to change batchsize, suddenly encountered it and there was no such error reported before, besides find the reg_feat as NaN tensor like the former one

 i met the same problem on v100,but i don't know the reason,can you provide some solutions,i am at a loss

**Comment by ilmoney** [comment]
> Did you modify any code?

i modify my code and met this problem,can you provide some solutions,i really don't know the reason

**Comment by bitzyz** [comment]
I face the same question , anyone can help me ?
log:
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [85,0,0], thread: [50,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [85,0,0], thread: [51,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [85,0,0], thread: [52,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [85,0,0], thread: [53,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [85,0,0], thread: [54,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [85,0,0], thread: [55,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [85,0,0], thread: [56,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [85,0,0], thread: [57,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [85,0,0], thread: [58,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [85,0,0], thread: [59,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [85,0,0], thread: [60,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [85,0,0], thread: [61,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [85,0,0], thread: [62,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [85,0,0], thread: [63,0,0] Assertion `input_val >= zero && input_val <= one` failed.
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCCachingHostAllocator.cpp line=278 error=710 : device-side assert triggered
2022-04-13 16:20:52 | ERROR    | yolox.models.yolo_head:330 - OOM RuntimeError is raised due to the huge memory cost during label assignment.                            CPU mode is applied in this batch. If you want to avoid this issue,                            try to reduce the batch size or image size.
2022-04-13 16:20:52 | INFO     | yolox.core.trainer:189 - Training of experiment is done and the best AP is 0.00
2022-04-13 16:20:52 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (24745), thread 'MainThread' (139972345780032):
Traceback (most recent call last):

  File "/home/zyz/Documents/YOLOX/yolox/models/yolo_head.py", line 324, in get_losses
    imgs,
    └ <unprintable Tensor object>

  File "/home/zyz/.conda/envs/py38/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ <unprintable tuple object>
           └ <function YOLOXHead.get_assignments at 0x7f4d655dc2f0>

  File "/home/zyz/Documents/YOLOX/yolox/models/yolo_head.py", line 519, in get_assignments
    cls_preds_.sqrt_(), gt_cls_per_image, reduction="none"
    │          │        └ <unprintable Tensor object>
    │          └ <method 'sqrt_' of 'torch._C._TensorBase' objects>
    └ <unprintable Tensor object>

  File "/home/zyz/.conda/envs/py38/lib/python3.7/site-packages/torch/nn/functional.py", line 2759, in binary_cross_entropy
    return torch._C._nn.binary_cross_entropy(input, target, weight, reduction_enum)
           │     │  │   │                    │      │       │       └ 0
           │     │  │   │                    │      │       └ None
           │     │  │   │                    │      └ <unprintable Tensor object>
           │     │  │   │                    └ <unprintable Tensor object>
           │     │  │   └ <built-in function binary_cross_entropy>
           │     │  └ <module 'torch._C._nn'>
           │     └ <module 'torch._C' from '/home/zyz/.conda/envs/py38/lib/python3.7/site-packages/torch/_C.cpython-37m-x86_64-linux-gnu.so'>
           └ <module 'torch' from '/home/zyz/.conda/envs/py38/lib/python3.7/site-packages/torch/__init__.py'>

RuntimeError: CUDA error: device-side assert triggered

@FateScript

**Comment by ilmoney** [comment]
maybe you can check you environment,and is the version of python 3.8?

**Comment by kuazhangxiaoai** [comment]
I'm confused about this problem too

**Comment by wangyirui** [comment]
我开始也遇到同样的问题，是Tesla V100。后来把Batch size从48一路尝试降到16后就没出现过这个问题了。GPU内存应该是足够的，不知道为什么batch size会导致这个错误。不知道会不会因为大batch在做mixed precision的时候导致gradient有问题？因为我观测到报错前有些iter会出现nan的loss

**Comment by Yuanyang-Zhu** [comment]
Setting the learning rate a little smaller can solve this problem. In fact, I succeeded.

**Comment by ailias** [comment]
> Setting the learning rate a little smaller can solve this problem. In fact, I succeeded.

So why large lr may cause this problem?

**Comment by GuoXu-booo** [comment]
About this problem, I finally found that the gpu is broken. You need to change the CPU to run the yolox code to determine whether there is a problem with your code

**Comment by lmw0320** [comment]
Had there anyone fixed it? I met the same problem。。。Any I have tried to reduce the lr and batch-size，still useless......
And that's my GPU device shown below:
![1](https://user-images.githubusercontent.com/37755235/177664367-538642e2-2c02-46a2-8eb3-97c1050d23e3.png)
I run my code in docker container. And I have run others code using the GPU without any problem...
Also, I have run the same code with same setting of batch-size and lr  before in similar docker container successfully.

**Comment by GuoXu-booo** [comment]
> 有人修过吗？我遇到了同样的问题。。。任何我尝试过减少lr和batch-size，仍然没用...... 这是我的GPU设备，如下所示： 我在docker容器中运行我的代码。而且我已经使用 GPU 运行其他代码没有任何问题...... 此外，我之前在类似的 docker 容器中成功地运行了具有相同批处理大小和 lr 设置的相同代码。 ![1](https://user-images.githubusercontent.com/37755235/177664367-538642e2-2c02-46a2-8eb3-97c1050d23e3.png)

You first switch to CPU to run YOLOX, to confirm that it is not a problem with the code

**Comment by lmw0320** [comment]
> 

how to switch to CPU? by any simple parameter setting?

**Comment by iodncookie** [comment]
i also met this question, after i add siou loss and uesed it...

**Comment by nanhai78** [comment]
I met same problem.Then, I can train normally after turning off fp16

**Comment by nuaaaaa** [comment]
同样出现前向NAN的问题，降低学习率也不work，初步确定是BN的weight的问题，修改BN初始化时weight的分布，其方差变小是work的，但是学不动，ap=0。建议将网络中所有BN改为GN，我这可以成功解决此问题。

**Comment by lawrencekiba** [comment]
> I met same problem.Then, I can train normally after turning off fp16

This worked for me, thank you

**Comment by gachiemchiep** [comment]
Anyone solved this problems ?
I tried everything suggested here such as : reduce lr, turning off fp16, reduce batch size, turn off cache. I even switch yolox back to 0.2.0, switch python version. 
But nothing worked. ....

**Comment by flyingfish7777** [comment]
> I met same problem.Then, I can train normally after turning off fp16

omg!!!!!thank   you  ！  useful！

**Comment by chairc** [comment]
> Anyone solved this problems ? I tried everything suggested here such as : reduce lr, turning off fp16, reduce batch size, turn off cache. I even switch yolox back to 0.2.0, switch python version. But nothing worked. ....

Have you ever tried to change FOCUS to a normal 3*3 convolution?

**Comment by nuaaaaa** [comment]
可以试一下加载预训练模型或者将bn改成gn



---原始邮件---
发件人: "Yu ***@***.***&gt;
发送时间: 2022年11月7日(周一) 下午4:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Megvii-BaseDetection/YOLOX] 训练yolox-s出现RuntimeError: CUDA error: device-side assert triggered问题 (Issue #1161)




  
Anyone solved this problems ? I tried everything suggested here such as : reduce lr, turning off fp16, reduce batch size, turn off cache. I even switch yolox back to 0.2.0, switch python version. But nothing worked. ....
  
Have you ever tried to change FOCUS to a normal 3*3 convolution?

**Comment by Monkey-D-Luffy-star** [comment]
> i also met this question, after i add siou loss and uesed it...

What did you do to fix it?

**Comment by Holmes2002** [comment]
I resize my images and run succeded. I think It is a solution !

**Comment by fengkh** [comment]
> 

我认为是因为做了mosaic增强导致的，mosaic有些增强猛了会导致随机组合的图出来的gt超出了图片的范围，我现在训练都关mosaic的，就几乎没出过这个问题。

**Comment by fengkh** [comment]
> 同样遇到该问题，怎么解决的哇？

Reducing lr solves but I dont know why it happens.

**Comment by aisimusi** [comment]
i reduce learning rate and fix this
