### ISSUE TITLE
CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by dongdongyee** [Megvii-BaseDetection/YOLOX#117]
我替换了自己的数据集，COCO标注，一共两个类别。改动了一部分config后可以正常开始训练。关闭了apex加速。训练了几个epoch之后突然在某个step上loss飙升，mAP降至0。loss一段时间无法恢复，并在某个step报出CUDA error: device-side assert triggered. 训练曲线和错误信息如下。
![image](https://user-images.githubusercontent.com/57374924/126778900-57443103-189a-473b-b4a3-3f6ced0dd035.png)

2021-07-22 22:49:51.863 | INFO     | yolox.core.trainer:after_iter:252 - epoch: 11/70, iter: 320/464, mem: 9776Mb, iter_time: 0.538s, data_time: 0.002s, total_loss: 9.5, iou_loss: 3.7, l1_loss: 0.0, conf_loss: 4.6, cls_loss: 1.1, lr: 1.064e-03, size: 1280, ETA: 4:30:22
2021-07-22 22:49:53.647 | ERROR    | yolox.models.yolo_head:get_losses:290 - OOM RuntimeError is raised due to the huge memory cost during label assignment.                            CPU mode is applied in this batch. If you want to avoid this issue,                            try to reduce the batch size or image size.
2021-07-22 22:49:53.650 | INFO     | yolox.core.trainer:after_train:185 - Training of experiment is done and the best AP is 37.17
2021-07-22 22:49:53.652 | ERROR    | yolox.core.launch:_distributed_worker:104 - An error has been caught in function '_distributed_worker', process 'SpawnProcess-1' (1127), thread 'MainThread' (139630666147648):
Traceback (most recent call last):

  File "/local/YOLOX/yolox/models/yolo_head.py", line 284, in get_losses
    cls_preds, bbox_preds, obj_preds, labels, imgs,
    │          │           │          │       └ <unprintable Tensor object>
    │          │           │          └ <unprintable Tensor object>
    │          │           └ <unprintable Tensor object>
    │          └ <unprintable Tensor object>
    └ <unprintable Tensor object>

  File "/local/condaenvs/yolox/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ <unprintable tuple object>
           └ <function YOLOXHead.get_assignments at 0x7efd2ecfd320>

  File "/local/YOLOX/yolox/models/yolo_head.py", line 412, in get_assignments
    ) = self.dynamic_k_matching(cost, pair_wise_ious, gt_classes, num_gt, fg_mask)
        │    │                  │     │               │           │       └ <unprintable Tensor object>
        │    │                  │     │               │           └ 71
        │    │                  │     │               └ <unprintable Tensor object>
        │    │                  │     └ <unprintable Tensor object>
        │    │                  └ <unprintable Tensor object>
        │    └ <function YOLOXHead.dynamic_k_matching at 0x7efd2ecfd4d0>
        └ YOLOXHead(
            (cls_convs): ModuleList(
              (0): Sequential(
                (0): BaseConv(
                  (conv): Conv2d(256, 256, kernel_size=...

  File "/local/YOLOX/yolox/models/yolo_head.py", line 513, in dynamic_k_matching
    cost[gt_idx], k=dynamic_ks[gt_idx].item(), largest=False
    │    │          │          └ 0
    │    │          └ <unprintable Tensor object>
    │    └ 0
    └ <unprintable Tensor object>

RuntimeError: CUDA error: device-side assert triggered

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
               │     └ 33
               └ <function _main at 0x7efe4aff18c0>
  File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/spawn.py", line 118, in _main
    return self._bootstrap()
           │    └ <function BaseProcess._bootstrap at 0x7efe4b0f6290>
           └ <SpawnProcess(SpawnProcess-1, started)>
  File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7efe4b0f18c0>
    └ <SpawnProcess(SpawnProcess-1, started)>
  File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <SpawnProcess(SpawnProcess-1, started)>
    │    │        │    └ (<function _distributed_worker at 0x7efd4275ac20>, 0, (<function main at 0x7efe4ac31b90>, 7, 7, 0, 'nccl', 'tcp://127.0.0.1:5...
    │    │        └ <SpawnProcess(SpawnProcess-1, started)>
    │    └ <function _wrap at 0x7efd463869e0>
    └ <SpawnProcess(SpawnProcess-1, started)>
  File "/local/condaenvs/yolox/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
    │  │   └ (<function main at 0x7efe4ac31b90>, 7, 7, 0, 'nccl', 'tcp://127.0.0.1:50857', (╒══════════════════╤══════════════════════════...
    │  └ 0
    └ <function _distributed_worker at 0x7efd4275ac20>

> File "/local/YOLOX/yolox/core/launch.py", line 104, in _distributed_worker
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7efe4ac31b90>

  File "/local/YOLOX/tools/train.py", line 101, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7efd39160320>
    └ <yolox.core.trainer.Trainer object at 0x7efd37788d90>

  File "/local/YOLOX/yolox/core/trainer.py", line 70, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x7efd385809e0>
    └ <yolox.core.trainer.Trainer object at 0x7efd37788d90>

  File "/local/YOLOX/yolox/core/trainer.py", line 79, in train_in_epoch
    self.train_in_iter()
    │    └ <function Trainer.train_in_iter at 0x7efd38582c20>
    └ <yolox.core.trainer.Trainer object at 0x7efd37788d90>

  File "/local/YOLOX/yolox/core/trainer.py", line 85, in train_in_iter
    self.train_one_iter()
    │    └ <function Trainer.train_one_iter at 0x7efd36d09680>
    └ <yolox.core.trainer.Trainer object at 0x7efd37788d90>

  File "/local/YOLOX/yolox/core/trainer.py", line 97, in train_one_iter
    outputs = self.model(inps, targets)
              │    │     │     └ <unprintable Tensor object>
              │    │     └ <unprintable Tensor object>
              │    └ DistributedDataParallel(
              │        (module): YOLOX(
              │          (backbone): YOLOPAFPN(
              │            (backbone): CSPDarknet(
              │              (stem): Focus(
              │       ...
              └ <yolox.core.trainer.Trainer object at 0x7efd37788d90>

  File "/local/condaenvs/yolox/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
             │    │        │        └ {}
             │    │        └ <unprintable tuple object>
             │    └ <function DistributedDataParallel.forward at 0x7efd39158170>
             └ DistributedDataParallel(
                 (module): YOLOX(
                   (backbone): YOLOPAFPN(
                     (backbone): CSPDarknet(
                       (stem): Focus(
                ...
  File "/local/condaenvs/yolox/lib/python3.7/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
             │            │         └ {}
             │            └ <unprintable tuple object>
             └ DistributedDataParallel(
                 (module): YOLOX(
                   (backbone): YOLOPAFPN(
                     (backbone): CSPDarknet(
                       (stem): Focus(
                ...
  File "/local/condaenvs/yolox/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
             │    │        │        └ {}
             │    │        └ <unprintable tuple object>
             │    └ <function YOLOX.forward at 0x7efd2ecfdb00>
             └ YOLOX(
                 (backbone): YOLOPAFPN(
                   (backbone): CSPDarknet(
                     (stem): Focus(
                       (conv): BaseConv(
                         (conv): ...

  File "/local/YOLOX/yolox/models/yolox.py", line 35, in forward
    fpn_outs, targets, x
    │         │        └ <unprintable Tensor object>
    │         └ <unprintable Tensor object>
    └ <unprintable tuple object>

  File "/local/condaenvs/yolox/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
             │    │        │        └ {}
             │    │        └ <unprintable tuple object>
             │    └ <function YOLOXHead.forward at 0x7efd2ecfd050>
             └ YOLOXHead(
                 (cls_convs): ModuleList(
                   (0): Sequential(
                     (0): BaseConv(
                       (conv): Conv2d(256, 256, kernel_size=...

  File "/local/YOLOX/yolox/models/yolo_head.py", line 186, in forward
    torch.cat(outputs, 1), origin_preds, dtype=xin[0].dtype
    │     │   │            │                   └ <unprintable tuple object>
    │     │   │            └ []
    │     │   └ <unprintable list object>
    │     └ <built-in method cat of type object at 0x7efe495f95c0>
    └ <module 'torch' from '/local/condaenvs/yolox/lib/python3.7/site-packages/torch/__init__.py'>

  File "/local/YOLOX/yolox/models/yolo_head.py", line 292, in get_losses
    torch.cuda.empty_cache()
    │     │    └ <function empty_cache at 0x7efd46810290>
    │     └ <module 'torch.cuda' from '/local/condaenvs/yolox/lib/python3.7/site-packages/torch/cuda/__init__.py'>
    └ <module 'torch' from '/local/condaenvs/yolox/lib/python3.7/site-packages/torch/__init__.py'>

  File "/local/condaenvs/yolox/lib/python3.7/site-packages/torch/cuda/memory.py", line 87, in empty_cache
    torch._C._cuda_emptyCache()
    │     │  └ <built-in function _cuda_emptyCache>
    │     └ <module 'torch._C' from '/local/condaenvs/yolox/lib/python3.7/site-packages/torch/_C.cpython-37m-x86_64-linux-gnu.so'>
    └ <module 'torch' from '/local/condaenvs/yolox/lib/python3.7/site-packages/torch/__init__.py'>

RuntimeError: CUDA error: device-side assert triggered

我尝试关闭了Mosaic数据增强，再次开始训练，此时训练曲线比较正常，但某个时刻再次报出CUDA_ERROR. 训练曲线和报错信息如下：
![image](https://user-images.githubusercontent.com/57374924/126779589-d5fa2f96-28e1-44ba-a64e-4da9dc4e9a00.png)

![image](https://user-images.githubusercontent.com/57374924/126779835-8ac2a3c4-28d4-4c6f-817f-c3a9d1700cab.png)

**Comment by ruinmessi** [comment]
2021-07-22 22:49:53.647 | ERROR | yolox.models.yolo_head:get_losses:290 - OOM RuntimeError is raised due to the huge memory cost during label assignment. CPU mode is applied in this batch. If you want to avoid this issue, try to reduce the batch size or image size.

触发这段代码说明GPU的显存几乎满了。建议训练脚本加上`-o` 或者降低batchsize

**Comment by dongdongyee** [comment]
感谢您的回复， 训练脚本加上了-o 而且batchsize 只是2，最大图片尺寸为1280. 查看显存占用时也还很宽裕。请问是什么原因呢？今天resume了，跑了几个epoch又报了下面这个CUDAerror。

2021-07-26 12:27:59 | INFO     | yolox.core.trainer:305 - 
Average forward time: 37.26 ms, Average NMS time: 1.53 ms, Average inference time: 38.78 ms
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.762
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.933
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.872
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.432
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.730
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.818
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.084
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.505
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.821
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.593
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.802
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.867

2021-07-26 12:27:59 | INFO     | yolox.core.trainer:314 - Save weights to ./output/no_mosaic
2021-07-26 12:28:02 | INFO     | yolox.core.trainer:189 - ---> start train epoch20
2021-07-26 12:28:13 | INFO     | yolox.core.trainer:252 - epoch: 20/50, iter: 20/812, mem: 9553Mb, iter_time: 0.527s, data_time: 0.001s, total_loss: 2.1, iou_loss: 1.0, l1_loss: 0.0, conf_loss: 0.8, cls_loss: 0.3, lr: 4.491e-04, size: 864, ETA: 3:38:01
2021-07-26 12:28:23 | INFO     | yolox.core.trainer:252 - epoch: 20/50, iter: 40/812, mem: 9553Mb, iter_time: 0.495s, data_time: 0.001s, total_loss: 1.4, iou_loss: 0.8, l1_loss: 0.0, conf_loss: 0.3, cls_loss: 0.3, lr: 4.485e-04, size: 1056, ETA: 3:37:46
2021-07-26 12:28:34 | INFO     | yolox.core.trainer:252 - epoch: 20/50, iter: 60/812, mem: 9553Mb, iter_time: 0.549s, data_time: 0.001s, total_loss: 1.5, iou_loss: 0.8, l1_loss: 0.0, conf_loss: 0.4, cls_loss: 0.3, lr: 4.480e-04, size: 960, ETA: 3:37:41
terminate called after throwing an instance of 'c10::Error'
  **what():  CUDA error: an illegal memory access was encountered**
Exception raised from create_event_internal at /pytorch/c10/cuda/CUDACachingAllocator.cpp:687 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f5f151468b2 in /local/condaenvs/yolox/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0xad2 (0x7f5f15398952 in /local/condaenvs/yolox/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7f5f15131b7d in /local/condaenvs/yolox/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x60253a (0x7f5fb0a4d53a in /local/condaenvs/yolox/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x6025e6 (0x7f5fb0a4d5e6 in /local/condaenvs/yolox/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x192a10 (0x561d07efda10 in /local/condaenvs/yolox/bin/python)
frame #6: <unknown function> + 0x13aca8 (0x561d07ea5ca8 in /local/condaenvs/yolox/bin/python)
frame #7: <unknown function> + 0x13b5c8 (0x561d07ea65c8 in /local/condaenvs/yolox/bin/python)
frame #8: <unknown function> + 0x13b60e (0x561d07ea660e in /local/condaenvs/yolox/bin/python)
frame #9: <unknown function> + 0x13b60e (0x561d07ea660e in /local/condaenvs/yolox/bin/python)
frame #10: <unknown function> + 0x13b60e (0x561d07ea660e in /local/condaenvs/yolox/bin/python)
frame #11: <unknown function> + 0x13b60e (0x561d07ea660e in /local/condaenvs/yolox/bin/python)
frame #12: <unknown function> + 0x13b60e (0x561d07ea660e in /local/condaenvs/yolox/bin/python)
frame #13: <unknown function> + 0x11a748 (0x561d07e85748 in /local/condaenvs/yolox/bin/python)
frame #14: _PyEval_EvalCodeWithName + 0x824 (0x561d07eb1d04 in /local/condaenvs/yolox/bin/python)
frame #15: _PyFunction_FastCallDict + 0x1ce (0x561d07eb24fe in /local/condaenvs/yolox/bin/python)
frame #16: _PyEval_EvalFrameDefault + 0x46fd (0x561d07f13f0d in /local/condaenvs/yolox/bin/python)
frame #17: _PyFunction_FastCallDict + 0x117 (0x561d07eb2447 in /local/condaenvs/yolox/bin/python)
frame #18: _PyEval_EvalFrameDefault + 0x46fd (0x561d07f13f0d in /local/condaenvs/yolox/bin/python)
frame #19: _PyFunction_FastCallDict + 0x117 (0x561d07eb2447 in /local/condaenvs/yolox/bin/python)
frame #20: _PyEval_EvalFrameDefault + 0x46fd (0x561d07f13f0d in /local/condaenvs/yolox/bin/python)
frame #21: _PyFunction_FastCallKeywords + 0xf8 (0x561d07edf758 in /local/condaenvs/yolox/bin/python)
frame #22: <unknown function> + 0x1913a5 (0x561d07efc3a5 in /local/condaenvs/yolox/bin/python)
frame #23: _PyEval_EvalFrameDefault + 0x90a (0x561d07f1011a in /local/condaenvs/yolox/bin/python)
frame #24: _PyFunction_FastCallKeywords + 0xf8 (0x561d07edf758 in /local/condaenvs/yolox/bin/python)
frame #25: <unknown function> + 0x1913a5 (0x561d07efc3a5 in /local/condaenvs/yolox/bin/python)
frame #26: _PyEval_EvalFrameDefault + 0x90a (0x561d07f1011a in /local/condaenvs/yolox/bin/python)
frame #27: _PyFunction_FastCallKeywords + 0xf8 (0x561d07edf758 in /local/condaenvs/yolox/bin/python)
frame #28: <unknown function> + 0x1913a5 (0x561d07efc3a5 in /local/condaenvs/yolox/bin/python)
frame #29: _PyEval_EvalFrameDefault + 0x7c9 (0x561d07f0ffd9 in /local/condaenvs/yolox/bin/python)
frame #30: _PyEval_EvalCodeWithName + 0x1cd (0x561d07eb16ad in /local/condaenvs/yolox/bin/python)
frame #31: _PyFunction_FastCallKeywords + 0x491 (0x561d07edfaf1 in /local/condaenvs/yolox/bin/python)
frame #32: <unknown function> + 0x1913a5 (0x561d07efc3a5 in /local/condaenvs/yolox/bin/python)
frame #33: _PyEval_EvalFrameDefault + 0x1956 (0x561d07f11166 in /local/condaenvs/yolox/bin/python)
frame #34: _PyEval_EvalCodeWithName + 0x1cd (0x561d07eb16ad in /local/condaenvs/yolox/bin/python)
frame #35: PyEval_EvalCode + 0x23 (0x561d07f01963 in /local/condaenvs/yolox/bin/python)
frame #36: <unknown function> + 0x1ed176 (0x561d07f58176 in /local/condaenvs/yolox/bin/python)
frame #37: PyRun_StringFlags + 0x7d (0x561d07f59aed in /local/condaenvs/yolox/bin/python)
frame #38: PyRun_SimpleStringFlags + 0x3c (0x561d07f59b4c in /local/condaenvs/yolox/bin/python)
frame #39: <unknown function> + 0x1eec4a (0x561d07f59c4a in /local/condaenvs/yolox/bin/python)
frame #40: _Py_UnixMain + 0x3c (0x561d07f5a00c in /local/condaenvs/yolox/bin/python)
frame #41: __libc_start_main + 0xf5 (0x7f5fb33ca555 in /usr/lib64/libc.so.6)
frame #42: <unknown function> + 0x1c24db (0x561d07f2d4db in /local/condaenvs/yolox/bin/python)

Process Process-4:1:
Traceback (most recent call last):
  File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/local/condaenvs/yolox/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 171, in _worker_loop
    r = index_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/local/condaenvs/yolox/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 282, in rebuild_storage_fd
    fd = df.detach()
  File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/connection.py", line 498, in Client
    answer_challenge(c, authkey)
  File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/connection.py", line 742, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Process Process-1:1:
Traceback (most recent call last):
  File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/local/condaenvs/yolox/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 171, in _worker_loop
    r = index_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/local/condaenvs/yolox/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 282, in rebuild_storage_fd
    fd = df.detach()
  File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/connection.py", line 498, in Client
    answer_challenge(c, authkey)
  File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/connection.py", line 742, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
/local/condaenvs/yolox/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 14 leaked semaphores to clean up at shutdown
  len(cache))
/local/condaenvs/yolox/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 23 leaked semaphores to clean up at shutdown
  len(cache))
/local/condaenvs/yolox/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 14 leaked semaphores to clean up at shutdown
  len(cache))
Traceback (most recent call last):
  File "tools/train.py", line 115, in <module>
    dist_url=dist_url, args=(exp, args)
  File "/local/YOLOX/yolox/core/launch.py", line 65, in launch
    daemon=False,
  File "/local/condaenvs/yolox/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/local/condaenvs/yolox/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/local/condaenvs/yolox/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 107, in join
    (error_index, name)

**Comment by monsterlyg** [comment]
> 感谢您的回复， 训练脚本加上了-o 而且batchsize 只是2，最大图片尺寸为1280. 查看显存占用时也还很宽裕。请问是什么原因呢？今天resume了，跑了几个epoch又报了下面这个CUDAerror。
> 
> 2021-07-26 12:27:59 | INFO | yolox.core.trainer:305 -
> Average forward time: 37.26 ms, Average NMS time: 1.53 ms, Average inference time: 38.78 ms
> Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.762
> Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=100 ] = 0.933
> Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=100 ] = 0.872
> Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.432
> Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.730
> Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.818
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 1 ] = 0.084
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 10 ] = 0.505
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.821
> Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.593
> Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.802
> Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.867
> 
> 2021-07-26 12:27:59 | INFO | yolox.core.trainer:314 - Save weights to ./output/no_mosaic
> 2021-07-26 12:28:02 | INFO | yolox.core.trainer:189 - ---> start train epoch20
> 2021-07-26 12:28:13 | INFO | yolox.core.trainer:252 - epoch: 20/50, iter: 20/812, mem: 9553Mb, iter_time: 0.527s, data_time: 0.001s, total_loss: 2.1, iou_loss: 1.0, l1_loss: 0.0, conf_loss: 0.8, cls_loss: 0.3, lr: 4.491e-04, size: 864, ETA: 3:38:01
> 2021-07-26 12:28:23 | INFO | yolox.core.trainer:252 - epoch: 20/50, iter: 40/812, mem: 9553Mb, iter_time: 0.495s, data_time: 0.001s, total_loss: 1.4, iou_loss: 0.8, l1_loss: 0.0, conf_loss: 0.3, cls_loss: 0.3, lr: 4.485e-04, size: 1056, ETA: 3:37:46
> 2021-07-26 12:28:34 | INFO | yolox.core.trainer:252 - epoch: 20/50, iter: 60/812, mem: 9553Mb, iter_time: 0.549s, data_time: 0.001s, total_loss: 1.5, iou_loss: 0.8, l1_loss: 0.0, conf_loss: 0.4, cls_loss: 0.3, lr: 4.480e-04, size: 960, ETA: 3:37:41
> terminate called after throwing an instance of 'c10::Error'
> **what(): CUDA error: an illegal memory access was encountered**
> Exception raised from create_event_internal at /pytorch/c10/cuda/CUDACachingAllocator.cpp:687 (most recent call first):
> frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f5f151468b2 in /local/condaenvs/yolox/lib/python3.7/site-packages/torch/lib/libc10.so)
> frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0xad2 (0x7f5f15398952 in /local/condaenvs/yolox/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
> frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7f5f15131b7d in /local/condaenvs/yolox/lib/python3.7/site-packages/torch/lib/libc10.so)
> frame #3: + 0x60253a (0x7f5fb0a4d53a in /local/condaenvs/yolox/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
> frame #4: + 0x6025e6 (0x7f5fb0a4d5e6 in /local/condaenvs/yolox/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
> frame #5: + 0x192a10 (0x561d07efda10 in /local/condaenvs/yolox/bin/python)
> frame #6: + 0x13aca8 (0x561d07ea5ca8 in /local/condaenvs/yolox/bin/python)
> frame #7: + 0x13b5c8 (0x561d07ea65c8 in /local/condaenvs/yolox/bin/python)
> frame #8: + 0x13b60e (0x561d07ea660e in /local/condaenvs/yolox/bin/python)
> frame #9: + 0x13b60e (0x561d07ea660e in /local/condaenvs/yolox/bin/python)
> frame #10: + 0x13b60e (0x561d07ea660e in /local/condaenvs/yolox/bin/python)
> frame #11: + 0x13b60e (0x561d07ea660e in /local/condaenvs/yolox/bin/python)
> frame #12: + 0x13b60e (0x561d07ea660e in /local/condaenvs/yolox/bin/python)
> frame #13: + 0x11a748 (0x561d07e85748 in /local/condaenvs/yolox/bin/python)
> frame #14: _PyEval_EvalCodeWithName + 0x824 (0x561d07eb1d04 in /local/condaenvs/yolox/bin/python)
> frame #15: _PyFunction_FastCallDict + 0x1ce (0x561d07eb24fe in /local/condaenvs/yolox/bin/python)
> frame #16: _PyEval_EvalFrameDefault + 0x46fd (0x561d07f13f0d in /local/condaenvs/yolox/bin/python)
> frame #17: _PyFunction_FastCallDict + 0x117 (0x561d07eb2447 in /local/condaenvs/yolox/bin/python)
> frame #18: _PyEval_EvalFrameDefault + 0x46fd (0x561d07f13f0d in /local/condaenvs/yolox/bin/python)
> frame #19: _PyFunction_FastCallDict + 0x117 (0x561d07eb2447 in /local/condaenvs/yolox/bin/python)
> frame #20: _PyEval_EvalFrameDefault + 0x46fd (0x561d07f13f0d in /local/condaenvs/yolox/bin/python)
> frame #21: _PyFunction_FastCallKeywords + 0xf8 (0x561d07edf758 in /local/condaenvs/yolox/bin/python)
> frame #22: + 0x1913a5 (0x561d07efc3a5 in /local/condaenvs/yolox/bin/python)
> frame #23: _PyEval_EvalFrameDefault + 0x90a (0x561d07f1011a in /local/condaenvs/yolox/bin/python)
> frame #24: _PyFunction_FastCallKeywords + 0xf8 (0x561d07edf758 in /local/condaenvs/yolox/bin/python)
> frame #25: + 0x1913a5 (0x561d07efc3a5 in /local/condaenvs/yolox/bin/python)
> frame #26: _PyEval_EvalFrameDefault + 0x90a (0x561d07f1011a in /local/condaenvs/yolox/bin/python)
> frame #27: _PyFunction_FastCallKeywords + 0xf8 (0x561d07edf758 in /local/condaenvs/yolox/bin/python)
> frame #28: + 0x1913a5 (0x561d07efc3a5 in /local/condaenvs/yolox/bin/python)
> frame #29: _PyEval_EvalFrameDefault + 0x7c9 (0x561d07f0ffd9 in /local/condaenvs/yolox/bin/python)
> frame #30: _PyEval_EvalCodeWithName + 0x1cd (0x561d07eb16ad in /local/condaenvs/yolox/bin/python)
> frame #31: _PyFunction_FastCallKeywords + 0x491 (0x561d07edfaf1 in /local/condaenvs/yolox/bin/python)
> frame #32: + 0x1913a5 (0x561d07efc3a5 in /local/condaenvs/yolox/bin/python)
> frame #33: _PyEval_EvalFrameDefault + 0x1956 (0x561d07f11166 in /local/condaenvs/yolox/bin/python)
> frame #34: _PyEval_EvalCodeWithName + 0x1cd (0x561d07eb16ad in /local/condaenvs/yolox/bin/python)
> frame #35: PyEval_EvalCode + 0x23 (0x561d07f01963 in /local/condaenvs/yolox/bin/python)
> frame #36: + 0x1ed176 (0x561d07f58176 in /local/condaenvs/yolox/bin/python)
> frame #37: PyRun_StringFlags + 0x7d (0x561d07f59aed in /local/condaenvs/yolox/bin/python)
> frame #38: PyRun_SimpleStringFlags + 0x3c (0x561d07f59b4c in /local/condaenvs/yolox/bin/python)
> frame #39: + 0x1eec4a (0x561d07f59c4a in /local/condaenvs/yolox/bin/python)
> frame #40: _Py_UnixMain + 0x3c (0x561d07f5a00c in /local/condaenvs/yolox/bin/python)
> frame #41: __libc_start_main + 0xf5 (0x7f5fb33ca555 in /usr/lib64/libc.so.6)
> frame #42: + 0x1c24db (0x561d07f2d4db in /local/condaenvs/yolox/bin/python)
> 
> Process Process-4:1:
> Traceback (most recent call last):
> File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
> self.run()
> File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/process.py", line 99, in run
> self._target(*self._args, **self._kwargs)
> File "/local/condaenvs/yolox/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 171, in _worker_loop
> r = index_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
> File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/queues.py", line 113, in get
> return _ForkingPickler.loads(res)
> File "/local/condaenvs/yolox/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 282, in rebuild_storage_fd
> fd = df.detach()
> File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
> with _resource_sharer.get_connection(self._id) as conn:
> File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
> c = Client(address, authkey=process.current_process().authkey)
> File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/connection.py", line 498, in Client
> answer_challenge(c, authkey)
> File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/connection.py", line 742, in answer_challenge
> message = connection.recv_bytes(256) # reject large message
> File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
> buf = self._recv_bytes(maxlength)
> File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
> buf = self._recv(4)
> File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
> chunk = read(handle, remaining)
> ConnectionResetError: [Errno 104] Connection reset by peer
> Process Process-1:1:
> Traceback (most recent call last):
> File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
> self.run()
> File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/process.py", line 99, in run
> self._target(*self._args, **self._kwargs)
> File "/local/condaenvs/yolox/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 171, in _worker_loop
> r = index_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
> File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/queues.py", line 113, in get
> return _ForkingPickler.loads(res)
> File "/local/condaenvs/yolox/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 282, in rebuild_storage_fd
> fd = df.detach()
> File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
> with _resource_sharer.get_connection(self._id) as conn:
> File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
> c = Client(address, authkey=process.current_process().authkey)
> File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/connection.py", line 498, in Client
> answer_challenge(c, authkey)
> File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/connection.py", line 742, in answer_challenge
> message = connection.recv_bytes(256) # reject large message
> File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
> buf = self._recv_bytes(maxlength)
> File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
> buf = self._recv(4)
> File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
> raise EOFError
> EOFError
> /local/condaenvs/yolox/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 14 leaked semaphores to clean up at shutdown
> len(cache))
> /local/condaenvs/yolox/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 23 leaked semaphores to clean up at shutdown
> len(cache))
> /local/condaenvs/yolox/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 14 leaked semaphores to clean up at shutdown
> len(cache))
> Traceback (most recent call last):
> File "tools/train.py", line 115, in
> dist_url=dist_url, args=(exp, args)
> File "/local/YOLOX/yolox/core/launch.py", line 65, in launch
> daemon=False,
> File "/local/condaenvs/yolox/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
> return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
> File "/local/condaenvs/yolox/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
> while not context.join():
> File "/local/condaenvs/yolox/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 107, in join
> (error_index, name)

我在训练m模型的时候也是一只这个错误

**Comment by uefall** [comment]
same issue crash in gpu mode get_assignments
感觉这个函数是不是有点问题

**Comment by uefall** [comment]
同样崩在gpu模式的get_assignments里
4卡2080ti 12G，batchsize=32

**Comment by MollyHoo** [comment]
1卡gtx1080 8G，batchsize=1，同样错误

**Comment by wawaa** [comment]
I meet the same problem.

**Comment by wawaa** [comment]
@dongdongyee @uefall @MollyHoo  Plus 1 to the self.num_classes maybe helps.

**Comment by vanity1129** [comment]
这个问题有人解决了吗，同样卡在这里 @ruinmessi

**Comment by vanity1129** [comment]
@ruinmessi @uefall @MollyHoo @wawaa @monsterlyg 有解决办法吗~

**Comment by oreo-lp** [comment]
batch size = 1，解决了这个问题

**Comment by pingjun18-li** [comment]
> > 感谢您的回复， 训练脚本加上了-o 而且batchsize 只是2，最大图片尺寸为1280. 查看显存占用时也还很宽裕。请问是什么原因呢？今天resume了，跑了几个epoch又报了下面这个CUDAerror。
> > 2021-07-26 12:27:59 | INFO | yolox.core.trainer:305 -
> > Average forward time: 37.26 ms, Average NMS time: 1.53 ms, Average inference time: 38.78 ms
> > Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.762
> > Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=100 ] = 0.933
> > Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=100 ] = 0.872
> > Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.432
> > Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.730
> > Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.818
> > Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 1 ] = 0.084
> > Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 10 ] = 0.505
> > Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.821
> > Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.593
> > Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.802
> > Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.867
> > 2021-07-26 12:27:59 | INFO | yolox.core.trainer:314 - Save weights to ./output/no_mosaic
> > 2021-07-26 12:28:02 | INFO | yolox.core.trainer:189 - ---> start train epoch20
> > 2021-07-26 12:28:13 | INFO | yolox.core.trainer:252 - epoch: 20/50, iter: 20/812, mem: 9553Mb, iter_time: 0.527s, data_time: 0.001s, total_loss: 2.1, iou_loss: 1.0, l1_loss: 0.0, conf_loss: 0.8, cls_loss: 0.3, lr: 4.491e-04, size: 864, ETA: 3:38:01
> > 2021-07-26 12:28:23 | INFO | yolox.core.trainer:252 - epoch: 20/50, iter: 40/812, mem: 9553Mb, iter_time: 0.495s, data_time: 0.001s, total_loss: 1.4, iou_loss: 0.8, l1_loss: 0.0, conf_loss: 0.3, cls_loss: 0.3, lr: 4.485e-04, size: 1056, ETA: 3:37:46
> > 2021-07-26 12:28:34 | INFO | yolox.core.trainer:252 - epoch: 20/50, iter: 60/812, mem: 9553Mb, iter_time: 0.549s, data_time: 0.001s, total_loss: 1.5, iou_loss: 0.8, l1_loss: 0.0, conf_loss: 0.4, cls_loss: 0.3, lr: 4.480e-04, size: 960, ETA: 3:37:41
> > terminate called after throwing an instance of 'c10::Error'
> > **what(): CUDA error: an illegal memory access was encountered**
> > Exception raised from create_event_internal at /pytorch/c10/cuda/CUDACachingAllocator.cpp:687 (most recent call first):
> > frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f5f151468b2 in /local/condaenvs/yolox/lib/python3.7/site-packages/torch/lib/libc10.so)
> > frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0xad2 (0x7f5f15398952 in /local/condaenvs/yolox/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
> > frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7f5f15131b7d in /local/condaenvs/yolox/lib/python3.7/site-packages/torch/lib/libc10.so)
> > frame #3: + 0x60253a (0x7f5fb0a4d53a in /local/condaenvs/yolox/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
> > frame #4: + 0x6025e6 (0x7f5fb0a4d5e6 in /local/condaenvs/yolox/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
> > frame #5: + 0x192a10 (0x561d07efda10 in /local/condaenvs/yolox/bin/python)
> > frame #6: + 0x13aca8 (0x561d07ea5ca8 in /local/condaenvs/yolox/bin/python)
> > frame #7: + 0x13b5c8 (0x561d07ea65c8 in /local/condaenvs/yolox/bin/python)
> > frame #8: + 0x13b60e (0x561d07ea660e in /local/condaenvs/yolox/bin/python)
> > frame #9: + 0x13b60e (0x561d07ea660e in /local/condaenvs/yolox/bin/python)
> > frame #10: + 0x13b60e (0x561d07ea660e in /local/condaenvs/yolox/bin/python)
> > frame #11: + 0x13b60e (0x561d07ea660e in /local/condaenvs/yolox/bin/python)
> > frame #12: + 0x13b60e (0x561d07ea660e in /local/condaenvs/yolox/bin/python)
> > frame #13: + 0x11a748 (0x561d07e85748 in /local/condaenvs/yolox/bin/python)
> > frame #14: _PyEval_EvalCodeWithName + 0x824 (0x561d07eb1d04 in /local/condaenvs/yolox/bin/python)
> > frame #15: _PyFunction_FastCallDict + 0x1ce (0x561d07eb24fe in /local/condaenvs/yolox/bin/python)
> > frame #16: _PyEval_EvalFrameDefault + 0x46fd (0x561d07f13f0d in /local/condaenvs/yolox/bin/python)
> > frame #17: _PyFunction_FastCallDict + 0x117 (0x561d07eb2447 in /local/condaenvs/yolox/bin/python)
> > frame #18: _PyEval_EvalFrameDefault + 0x46fd (0x561d07f13f0d in /local/condaenvs/yolox/bin/python)
> > frame #19: _PyFunction_FastCallDict + 0x117 (0x561d07eb2447 in /local/condaenvs/yolox/bin/python)
> > frame #20: _PyEval_EvalFrameDefault + 0x46fd (0x561d07f13f0d in /local/condaenvs/yolox/bin/python)
> > frame #21: _PyFunction_FastCallKeywords + 0xf8 (0x561d07edf758 in /local/condaenvs/yolox/bin/python)
> > frame #22: + 0x1913a5 (0x561d07efc3a5 in /local/condaenvs/yolox/bin/python)
> > frame #23: _PyEval_EvalFrameDefault + 0x90a (0x561d07f1011a in /local/condaenvs/yolox/bin/python)
> > frame #24: _PyFunction_FastCallKeywords + 0xf8 (0x561d07edf758 in /local/condaenvs/yolox/bin/python)
> > frame #25: + 0x1913a5 (0x561d07efc3a5 in /local/condaenvs/yolox/bin/python)
> > frame #26: _PyEval_EvalFrameDefault + 0x90a (0x561d07f1011a in /local/condaenvs/yolox/bin/python)
> > frame #27: _PyFunction_FastCallKeywords + 0xf8 (0x561d07edf758 in /local/condaenvs/yolox/bin/python)
> > frame #28: + 0x1913a5 (0x561d07efc3a5 in /local/condaenvs/yolox/bin/python)
> > frame #29: _PyEval_EvalFrameDefault + 0x7c9 (0x561d07f0ffd9 in /local/condaenvs/yolox/bin/python)
> > frame #30: _PyEval_EvalCodeWithName + 0x1cd (0x561d07eb16ad in /local/condaenvs/yolox/bin/python)
> > frame #31: _PyFunction_FastCallKeywords + 0x491 (0x561d07edfaf1 in /local/condaenvs/yolox/bin/python)
> > frame #32: + 0x1913a5 (0x561d07efc3a5 in /local/condaenvs/yolox/bin/python)
> > frame #33: _PyEval_EvalFrameDefault + 0x1956 (0x561d07f11166 in /local/condaenvs/yolox/bin/python)
> > frame #34: _PyEval_EvalCodeWithName + 0x1cd (0x561d07eb16ad in /local/condaenvs/yolox/bin/python)
> > frame #35: PyEval_EvalCode + 0x23 (0x561d07f01963 in /local/condaenvs/yolox/bin/python)
> > frame #36: + 0x1ed176 (0x561d07f58176 in /local/condaenvs/yolox/bin/python)
> > frame #37: PyRun_StringFlags + 0x7d (0x561d07f59aed in /local/condaenvs/yolox/bin/python)
> > frame #38: PyRun_SimpleStringFlags + 0x3c (0x561d07f59b4c in /local/condaenvs/yolox/bin/python)
> > frame #39: + 0x1eec4a (0x561d07f59c4a in /local/condaenvs/yolox/bin/python)
> > frame #40: _Py_UnixMain + 0x3c (0x561d07f5a00c in /local/condaenvs/yolox/bin/python)
> > frame #41: __libc_start_main + 0xf5 (0x7f5fb33ca555 in /usr/lib64/libc.so.6)
> > frame #42: + 0x1c24db (0x561d07f2d4db in /local/condaenvs/yolox/bin/python)
> > Process Process-4:1:
> > Traceback (most recent call last):
> > File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
> > self.run()
> > File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/process.py", line 99, in run
> > self._target(*self._args, **self._kwargs)
> > File "/local/condaenvs/yolox/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 171, in _worker_loop
> > r = index_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
> > File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/queues.py", line 113, in get
> > return _ForkingPickler.loads(res)
> > File "/local/condaenvs/yolox/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 282, in rebuild_storage_fd
> > fd = df.detach()
> > File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
> > with _resource_sharer.get_connection(self._id) as conn:
> > File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
> > c = Client(address, authkey=process.current_process().authkey)
> > File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/connection.py", line 498, in Client
> > answer_challenge(c, authkey)
> > File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/connection.py", line 742, in answer_challenge
> > message = connection.recv_bytes(256) # reject large message
> > File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
> > buf = self._recv_bytes(maxlength)
> > File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
> > buf = self._recv(4)
> > File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
> > chunk = read(handle, remaining)
> > ConnectionResetError: [Errno 104] Connection reset by peer
> > Process Process-1:1:
> > Traceback (most recent call last):
> > File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
> > self.run()
> > File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/process.py", line 99, in run
> > self._target(*self._args, **self._kwargs)
> > File "/local/condaenvs/yolox/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 171, in _worker_loop
> > r = index_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
> > File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/queues.py", line 113, in get
> > return _ForkingPickler.loads(res)
> > File "/local/condaenvs/yolox/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 282, in rebuild_storage_fd
> > fd = df.detach()
> > File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
> > with _resource_sharer.get_connection(self._id) as conn:
> > File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
> > c = Client(address, authkey=process.current_process().authkey)
> > File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/connection.py", line 498, in Client
> > answer_challenge(c, authkey)
> > File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/connection.py", line 742, in answer_challenge
> > message = connection.recv_bytes(256) # reject large message
> > File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
> > buf = self._recv_bytes(maxlength)
> > File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
> > buf = self._recv(4)
> > File "/local/condaenvs/yolox/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
> > raise EOFError
> > EOFError
> > /local/condaenvs/yolox/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 14 leaked semaphores to clean up at shutdown
> > len(cache))
> > /local/condaenvs/yolox/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 23 leaked semaphores to clean up at shutdown
> > len(cache))
> > /local/condaenvs/yolox/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 14 leaked semaphores to clean up at shutdown
> > len(cache))
> > Traceback (most recent call last):
> > File "tools/train.py", line 115, in
> > dist_url=dist_url, args=(exp, args)
> > File "/local/YOLOX/yolox/core/launch.py", line 65, in launch
> > daemon=False,
> > File "/local/condaenvs/yolox/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
> > return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
> > File "/local/condaenvs/yolox/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
> > while not context.join():
> > File "/local/condaenvs/yolox/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 107, in join
> > (error_index, name)
> 
> 我在训练m模型的时候也是一只这个错误

同样使用最新版本，自己的训练数据，仍然报错，求官方答案

**Comment by ujsyehao** [comment]
同样有问题，官方有注意到吗？

**Comment by tctco** [comment]
同样存在这个问题
