### ISSUE TITLE
yolox_s stuck when training custom data

### ISSUE THREAD

**Issue by xxcheng0708** [Megvii-BaseDetection/YOLOX#1281]
when training custom data with multi-gpus (I used 4 gpu devices), training process stuck, GPU memeory not released, and three gpus are in peak state, another one is empty。

![image](https://user-images.githubusercontent.com/33124611/165420664-c4ec3fcb-ee3b-41f7-bbd0-023c91343cae.png)
![image](https://user-images.githubusercontent.com/33124611/165420877-fbd43455-1169-4b30-97d3-28bf94486785.png)

I used the follwing training commands:
![image](https://user-images.githubusercontent.com/33124611/165421014-c705f838-61a0-4caf-a5ec-dc2bce4b3b4c.png)

**Comment by FateScript** [comment]
Your cuda memory is almost the upper bound, what if you reduce the batchsize?

**Comment by xxcheng0708** [comment]
Thank you for your excellent work. After reducing batch_size, my problem was solved. On our custom data set, after 300 epoch training, Yolox-S mAP was 4.4% higher than YoloV5-S.

**Comment by snehashis1997** [comment]
what should be the bs? I reduced to bs = 8 and d = 4, then also it got stuck after 1st epoch eval
