### ISSUE TITLE
multi GPU training gets stuck after first validation

### ISSUE THREAD

**Issue by paroj** [Megvii-BaseDetection/YOLOX#1316]
Does the evaluation keep some RAM allocated so that training starves?

Environment
- 8x NVIDIA A100-SXM4-40GB
- 960GB RAM allocated via Docker
- `docker run --shm-size=950g ..`
- `data_num_workers = 0`

e.g. with 8 GPUs, but also happens with 2 GPUs:
```
python -m yolox.tools.train -f exps/default/yolox_m.py -d 8 -b 64 -o --cache --fp16
```

end of log:
```
...
2022-05-13 18:29:45 | INFO     | yolox.core.trainer:352 - Save weights to ./YOLOX_outputs/yolox_m
2022-05-13 18:30:38 | INFO     | yolox.evaluators.coco_evaluator:235 - Evaluate in main process...
2022-05-13 18:30:49 | INFO     | yolox.evaluators.coco_evaluator:268 - Loading and preparing results...
2022-05-13 18:30:55 | INFO     | yolox.evaluators.coco_evaluator:268 - DONE (t=5.86s)
2022-05-13 18:30:55 | INFO     | pycocotools.coco:366 - creating index...
2022-05-13 18:30:55 | INFO     | pycocotools.coco:366 - index created!
[1/2] c++ -MMD -MF cocoeval.o.d -DTORCH_EXTENSION_NAME=fast_cocoeval -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1013\" -isystem /opt/conda/lib/python3.8/site-packages/torch/include -isystem /opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.8/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.8/site-packages/torch/include/THC -isystem /opt/conda/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++14 -O3 -std=c++14 -g -Wno-reorder -c /YOLOX/yolox/layers/cocoeval/cocoeval.cpp -o cocoeval.o 
[2/2] c++ cocoeval.o -shared -L/opt/conda/lib/python3.8/site-packages/torch/lib -lc10 -ltorch_cpu -ltorch -ltorch_python -o fast_cocoeval.so
2022-05-13 18:31:10 | INFO     | yolox.layers.jit_ops:111 - Load fast_cocoeval op in 14.323s.
2022-05-13 18:31:29 | INFO     | yolox.core.trainer:342 - 
Average forward time: 17.18 ms, Average NMS time: 3.09 ms, Average inference time: 20.28 ms
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.197
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.340
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.203
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.100
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.221
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.241
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.209
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.353
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.382
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.199
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.423
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.471
```

**Comment by DWendou** [comment]
same question，you have solved the question？

**Comment by FateScript** [comment]
I think stucking during traning might be caused by long time compile and evaluation on master process only. Is it producible and what's the platform are you using? WSL?

**Comment by FateScript** [comment]
duplicated with #1303

**Comment by paroj** [comment]
> I think stucking during traning might be caused by long time compile

compile took 15s, see
```
2022-05-13 18:31:10 | INFO     | yolox.layers.jit_ops:111 - Load fast_cocoeval op in 14.323s.
```
I will try baking this into the Docker image nevertheless.

Do you mean the 15s delay on the master process make the other trainer processes stuck?

> Is it producible and what's the platform are you using? WSL?

yes, this happens on every run. This uses `nvcr.io/nvidia/pytorch:22.04-py3` Docker image on a Ubuntu 20.04 Host.

**Comment by FateScript** [comment]
@paroj One possible way to workaround this issue is to compile the op at the begining (`python3 -m pip install -v -e .` first). It will compile fast_cocoeval and loading such operator might not take too much time.

**Comment by DWendou** [comment]
I didn't use version 0.3.0，I use 0.2.0 version can avoid this problem。

**Comment by paroj** [comment]
@FateScript 
I baked the compiled .so into the Docker Image with:
```
python -c "from yolox.layers import COCOeval_opt; COCOeval_opt()"
```
so it does not take any time:
```
2022-05-18 17:00:02 | INFO     | pycocotools.coco:366 - index created!
ninja: no work to do.
2022-05-18 17:00:04 | INFO     | yolox.layers.jit_ops:111 - Load fast_cocoeval op in 0.327s.
```

still, the training gets stuck as before after validation

**Comment by paroj** [comment]
ok, both downgrading to 0.2.0 and running `python3 -m pip install -v -e .` as suggested by @FateScript resolve the issue for me.

It seems that `wait_for_the_master` does not work properly and creates a deadlock if executed.

**Comment by FateScript** [comment]
@paroj Thanks for sharing. I'm wondering that will your progress gets stuck if you comment `wait_for_the_master`.

**Comment by DWendou** [comment]
> ok, both downgrading to 0.2.0 and running `python3 -m pip install -v -e .` as suggested by @FateScript resolve the issue for me.
> 
> It seems that `wait_for_the_master` does not work properly and creates a deadlock if executed.
Isn't it supposed to be thank me? A little upset

**Comment by paroj** [comment]
> I'm wondering that will your progress gets stuck if you comment wait_for_the_master.

training seems to proceed normally even without this line. I did not check the validation results, but if they are only computed on master, they should be fine.

Looking at
https://github.com/Megvii-BaseDetection/YOLOX/blob/68408b4083f818f50aacc29881e6f97cd19fcef2/yolox/utils/dist.py#L63-L72

I am not sure what it is supposed to do. Especially 
https://github.com/Megvii-BaseDetection/YOLOX/blob/68408b4083f818f50aacc29881e6f97cd19fcef2/yolox/utils/dist.py#L63-L64

seems off, as *all processes* need to enter `dist.barrier()` to continue. Were you thinking about mutex/ semaphore there maybe?

**Comment by FateScript** [comment]
@paroj Ok, I encounter a similar issue before and I think that a long-time compile and evaluation on master only cause the stuck. I will have a try on my own machine.

**Comment by nahidalam** [comment]
@paroj how are you installing yolox 0.2.0 ? When I do `pip3 install -v -e .` it gets `yolox==0.3.0` by default

**Comment by LorenzoSun-V** [comment]
> @paroj Ok, I encounter a similar issue before and I think that a long-time compile and evaluation on master only cause the stuck. I will have a try on my own machine.

Hi, have you solved this problem? I am encountering the same issue. The program stuck at the step after first evaluating.

**Comment by LorenzoSun-V** [comment]
> @paroj Ok, I encounter a similar issue before and I think that a long-time compile and evaluation on master only cause the stuck. I will have a try on my own machine.

I use
"""
pip install -v -e .
"""
to solve this by your advice in [#1289 ](https://github.com/Megvii-BaseDetection/YOLOX/issues/1289#issuecomment-1147343005). Thanks!

**Comment by ZXYFrank** [comment]
Hey guys. I found a workaround in my case.

(please fix me if I'm mistaken😉)

## only allow IP socket communication

try setting these variables, in the scripts or in python by using `os.environ[XXX] = ...`

```bash
export NCCL_LL_THRESHOLD=0
export NCCL_P2P_DISABLE=1
export NCCL_IB_DISABLE=1
```

The NCCL_P2P_DISABLE variable disables the peer to peer (P2P) transport, which uses CUDA direct access between GPUs, using NVLink or PCI.

The NCCL_IB_DISABLE variable disables the IB/RoCE transport that is to be used by NCCL. Instead, NCCL will fallback to using IP sockets.

## explanation

For distributed training, subprocesses are always initialized [dist.init_process_group](https://github.com/Megvii-BaseDetection/YOLOX/blob/f5331eaac5c03f73f59274522fe0507a030c5386/yolox/core/launch.py#L186-L190) by [TCP](https://github.com/Megvii-BaseDetection/YOLOX/blob/f5331eaac5c03f73f59274522fe0507a030c5386/yolox/core/launch.py#L106-L127)

So, IP communication seems reasonable.

_My colleague told me that on other machines, it may not need this kind of disabling and falling back to TCP. I donnot know why, either._

## caution

NCCL_LL_THRESHOLD is often set as zero. I don't know why.

`export NCCL_LL_THRESHOLD=0`

Caution ❗ They may influence the model performance.

https://github.com/NVIDIA/nccl/issues/369#issue-678319427

## change of start method

In [this commit](https://github.com/Megvii-BaseDetection/YOLOX/blame/026844ef96361983884eb611a89c58f3f53b66e0/yolox/core/launch.py) and before, multi-gpu subprocesses are started by `launch_by_subprocess`, which calls `subprocess.Popen`

_I use YOLOX in ByteTrack. It uses the old version of starting multiple processes_

```python
launch_by_subprocess(
        sys.argv,
        world_size,
        num_machines,
        machine_rank,
        num_gpus_per_machine,
        dist_url,
        args,
    )
```

In the subsequent commits, start methods are set to `mp.start_processes`, and there may also be some other related but hidden changes.

I haven't check whether switching to the later versions could directly fix the problem.❤️

I'm not familiar with CUDA or NCCL.

However, I think this workaround makes sense, in that it considers the communication between gpus, and the bug lie in the SYNCHRONIZATION.😃

**Comment by ctensmeyer** [comment]
I ran into this issue as well.  It is a sync bug that only happens if you JIT the faster COCOeval Op.  After the evaluation prediction loop and prediction gather, the non-main processes will block in `synchronize()` while the main process runs the evaluation code.  But when the main process has to JIT compile the eval op, it encounters a `wait_for_master()` synchronization call (used to prevent multiple processes from compiling at the same time) that uses the same `torch.distributed.barrier()` primitive as `synchronize()`.  This unblocks the non-main processes, so the main process gets stuck on that `synchronize()` once it finishes the COCOeval.

My fix is to just not use their custom COCOeval code.  The easiest way to do this is to modify `yolox/evaluators/coco_evaluator.py:evaluate_prediction()` so that it always fallsback to the `pycocotools` implementation by adding a `raise Exception()` within the `try` block where it attempts to import their COCOeval.

**Comment by YCAyca** [comment]
> ```shell
> export NCCL_LL_THRESHOLD=0
> export NCCL_P2P_DISABLE=1
> export NCCL_IB_DISABLE=1
> ```

This solution did not work for me ://
