### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 4.53 GiB

### ISSUE THREAD

**Issue by monkeycc** [Megvii-BaseDetection/YOLOX#665]
`python tools/train.py -f exps/example/custom/yolox_s.py -d 1 -b 1 --fp16 -o -c F:\YOLOX\yolox_s.pth`

`RuntimeError: CUDA out of memory. Tried to allocate 4.53 GiB (GPU 0; 6.00 GiB total capacity; 39.04 MiB already allocated; 4.45 GiB free; 64.00 MiB reserved in total by PyTorch)`

------------------
（在yolov5和paddle下都可以训练，环境没问题）

显卡 2060  6GB显存
CUDA Version: 11.2
数据集：coco128 （官方演示数据集）

是不是我还有配置文件没有调，还是只能换3060这些显卡？

**Comment by vasnakh** [comment]
I am also having the similar issue training on RTX 2080 Ti. The error is shown below:
RuntimeError: CUDA out of memory. Tried to allocate 14.17 GiB (GPU 0; 10.76 GiB total capacity; 132.73 MiB already allocated; 9.51 GiB free; 144.00 MiB reserved in total by PyTorch)


CUDA version 11.4, torch version 1.9

**Comment by monsterchan** [comment]
Delete the ‘-o’ in the command

**Comment by monsterchan** [comment]
there is  another way to solve it .  Please change 'yolox/utils/metric.py'. "x = torch.cuda.FloatTensor(256, 1024, block_mem)"--->x = torch.cuda.FloatTensor(256, 512, block_mem)

**Comment by monsterchan** [comment]
> `python tools/train.py -f exps/example/custom/yolox_s.py -d 1 -b 1 --fp16 -o -c F:\YOLOX\yolox_s.pth`
> 
> `RuntimeError: CUDA out of memory. Tried to allocate 4.53 GiB (GPU 0; 6.00 GiB total capacity; 39.04 MiB already allocated; 4.45 GiB free; 64.00 MiB reserved in total by PyTorch)`
> 
> （在yolov5和paddle下都可以训练，环境没问题）
> 
> 显卡 2060 6GB显存
> CUDA Version: 11.2
> 数据集：coco128 （官方演示数据集）
> 
> 是不是我还有配置文件没有调，还是只能换3060这些显卡？

如果显存还不够，将第二点说的第二个Tensor的尺寸再调小一点。我用的11G的显卡已经可以正常运行。

**Comment by ahmedanis03** [comment]
1. Don't use occupy -> delete the '-o' as @monsterchan said
2. disable pin memory in the data loader
```
dataloader_kwargs = {"num_workers": self.data_num_workers, "pin_memory": False}
```
3. reduce number of workers
4. 
This stabilized my training and let me train with much larger batch size

**Comment by ding19980201** [comment]
你的能训练了吗，batchsize是多少？

**Comment by ding19980201** [comment]
@monsterchan  你好，我delete -o pin_memory 为False num_workers为0 8G显卡batch_size 只能调到1  -f exps/example/mot/yolox_x_ablation.py 这个这么大吗
