### ISSUE TITLE
请问这个问题应该怎么解决

### ISSUE THREAD

**Issue by 18789447455** [Megvii-BaseDetection/YOLOX#738]
2021-09-24 21:52:39 | INFO     | yolox.core.trainer:188 - ---> start train epoch1
/home/zhaolimin/YOLOX
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:312: operator(): block: [0,0,0], thread: [13,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:312: operator(): block: [0,0,0], thread: [26,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
2021-09-24 21:52:41 | ERROR    | yolox.models.yolo_head:333 - OOM RuntimeError is raised due to the huge memory cost during label assignment.                            CPU mode is applied in this batch. If you want to avoid this issue,                            try to reduce the batch size or image size.
------------CPU Mode for This Batch-------------
2021-09-24 21:52:41 | INFO     | yolox.core.trainer:184 - Training of experiment is done and the best AP is 0.00
2021-09-24 21:52:41 | ERROR    | yolox.core.launch:149 - An error has been caught in function '_distributed_worker', process 'ForkProcess-1' (144370), thread 'MainThread' (140568597235456):
Traceback (most recent call last):

  File "/home/zhaolimin/YOLOX/yolox/models/yolo_head.py", line 327, in get_losses
    imgs,
    └ <unprintable Tensor object>

  File "/home/zhaolimin/anaconda3/envs/YOLOX/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ <unprintable tuple object>
           └ <function YOLOXHead.get_assignments at 0x7fd84fa7cd90>

  File "/home/zhaolimin/YOLOX/yolox/models/yolo_head.py", line 513, in get_assignments
    ) = self.dynamic_k_matching(cost, pair_wise_ious, gt_classes, num_gt, fg_mask)
        │    │                  │     │               │           │       └ <unprintable Tensor object>
        │    │                  │     │               │           └ 27
        │    │                  │     │               └ <unprintable Tensor object>
        │    │                  │     └ <unprintable Tensor object>
        │    │                  └ <unprintable Tensor object>
        │    └ <function YOLOXHead.dynamic_k_matching at 0x7fd84fa7cf28>
        └ YOLOXHead(
            (cls_convs): ModuleList(
              (0): Sequential(
                (0): BaseConv(
                  (conv): Conv2d(128, 128, kernel_size=...

  File "/home/zhaolimin/YOLOX/yolox/models/yolo_head.py", line 627, in dynamic_k_matching
    cost[gt_idx], k=dynamic_ks[gt_idx].item(), largest=False
    │    │          │          └ 0
    │    │          └ <unprintable Tensor object>
    │    └ 0
    └ <unprintable Tensor object>

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "tools/train.py", line 132, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=2, cache=True, ckpt=None, devices=2, dist_backend='nccl', dist_url=None, exp_file=None, experiment_name=...
          └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

  File "/home/zhaolimin/YOLOX/yolox/core/launch.py", line 97, in launch
    start_method=start_method,
                 └ 'fork'

  File "/home/zhaolimin/anaconda3/envs/YOLOX/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 179, in start_processes
    process.start()
    │       └ <function BaseProcess.start at 0x7fd8ab9fbe18>
    └ <ForkProcess(ForkProcess-1, started)>
  File "/home/zhaolimin/anaconda3/envs/YOLOX/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
    │    │        │    │      └ <ForkProcess(ForkProcess-1, started)>
    │    │        │    └ <staticmethod object at 0x7fd8aba04978>
    │    │        └ <ForkProcess(ForkProcess-1, started)>
    │    └ None
    └ <ForkProcess(ForkProcess-1, started)>
  File "/home/zhaolimin/anaconda3/envs/YOLOX/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
           │     └ <ForkProcess(ForkProcess-1, started)>
           └ <class 'multiprocessing.popen_fork.Popen'>
  File "/home/zhaolimin/anaconda3/envs/YOLOX/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
    │    │       └ <ForkProcess(ForkProcess-1, started)>
    │    └ <function Popen._launch at 0x7fd84fa4b0d0>
    └ <multiprocessing.popen_fork.Popen object at 0x7fd8ab78bef0>
  File "/home/zhaolimin/anaconda3/envs/YOLOX/lib/python3.7/multiprocessing/popen_fork.py", line 74, in _launch
    code = process_obj._bootstrap()
           │           └ <function BaseProcess._bootstrap at 0x7fd8aba0c730>
           └ <ForkProcess(ForkProcess-1, started)>
  File "/home/zhaolimin/anaconda3/envs/YOLOX/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7fd8ab9fbd90>
    └ <ForkProcess(ForkProcess-1, started)>
  File "/home/zhaolimin/anaconda3/envs/YOLOX/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <ForkProcess(ForkProcess-1, started)>
    │    │        │    └ (<function _distributed_worker at 0x7fd7e9132f28>, 0, (<function main at 0x7fd7dcaa61e0>, 2, 2, 0, 'nccl', 'tcp://127.0.0.1:4...
    │    │        └ <ForkProcess(ForkProcess-1, started)>
    │    └ <function _wrap at 0x7fd7ebc3f9d8>
    └ <ForkProcess(ForkProcess-1, started)>
  File "/home/zhaolimin/anaconda3/envs/YOLOX/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
    │  │   └ (<function main at 0x7fd7dcaa61e0>, 2, 2, 0, 'nccl', 'tcp://127.0.0.1:43552', (╒══════════════════╤══════════════════════════...
    │  └ 0
    └ <function _distributed_worker at 0x7fd7e9132f28>

> File "/home/zhaolimin/YOLOX/yolox/core/launch.py", line 149, in _distributed_worker
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7fd7dcaa61e0>

  File "tools/train.py", line 110, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7fd7ded0e620>
    └ <yolox.core.trainer.Trainer object at 0x7fd7dcaae438>

  File "/home/zhaolimin/YOLOX/yolox/core/trainer.py", line 72, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x7fd7dcd25510>
    └ <yolox.core.trainer.Trainer object at 0x7fd7dcaae438>

  File "/home/zhaolimin/YOLOX/yolox/core/trainer.py", line 81, in train_in_epoch
    self.train_in_iter()
    │    └ <function Trainer.train_in_iter at 0x7fd7dcd2eae8>
    └ <yolox.core.trainer.Trainer object at 0x7fd7dcaae438>

  File "/home/zhaolimin/YOLOX/yolox/core/trainer.py", line 87, in train_in_iter
    self.train_one_iter()
    │    └ <function Trainer.train_one_iter at 0x7fd7dcd2eb70>
    └ <yolox.core.trainer.Trainer object at 0x7fd7dcaae438>

  File "/home/zhaolimin/YOLOX/yolox/core/trainer.py", line 101, in train_one_iter
    outputs = self.model(inps, targets)
              │    │     │     └ <unprintable Tensor object>
              │    │     └ <unprintable Tensor object>
              │    └ DistributedDataParallel(
              │        (module): YOLOX(
              │          (backbone): YOLOPAFPN(
              │            (backbone): CSPDarknet(
              │              (stem): Focus(
              │       ...
              └ <yolox.core.trainer.Trainer object at 0x7fd7dcaae438>

  File "/home/zhaolimin/anaconda3/envs/YOLOX/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
           │             │        └ {}
           │             └ <unprintable tuple object>
           └ <bound method DistributedDataParallel.forward of DistributedDataParallel(
               (module): YOLOX(
                 (backbone): YOLOPAFPN(
                  ...
  File "/home/zhaolimin/anaconda3/envs/YOLOX/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 799, in forward
    output = self.module(*inputs[0], **kwargs[0])
             │            │            └ ({},)
             │            └ <unprintable tuple object>
             └ DistributedDataParallel(
                 (module): YOLOX(
                   (backbone): YOLOPAFPN(
                     (backbone): CSPDarknet(
                       (stem): Focus(
                ...
  File "/home/zhaolimin/anaconda3/envs/YOLOX/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
           │             │        └ {}
           │             └ <unprintable tuple object>
           └ <bound method YOLOX.forward of YOLOX(
               (backbone): YOLOPAFPN(
                 (backbone): CSPDarknet(
                   (stem): Focus(
                     (conv...

  File "/home/zhaolimin/YOLOX/yolox/models/yolox.py", line 35, in forward
    fpn_outs, targets, x
    │         │        └ <unprintable Tensor object>
    │         └ <unprintable Tensor object>
    └ <unprintable tuple object>

  File "/home/zhaolimin/anaconda3/envs/YOLOX/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
           │             │        └ {}
           │             └ <unprintable tuple object>
           └ <bound method YOLOXHead.forward of YOLOXHead(
               (cls_convs): ModuleList(
                 (0): Sequential(
                   (0): BaseConv(
                     (c...

  File "/home/zhaolimin/YOLOX/yolox/models/yolo_head.py", line 203, in forward
    dtype=xin[0].dtype,
          └ <unprintable tuple object>

  File "/home/zhaolimin/YOLOX/yolox/models/yolo_head.py", line 357, in get_losses
    "cpu",

  File "/home/zhaolimin/anaconda3/envs/YOLOX/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ <unprintable tuple object>
           └ <function YOLOXHead.get_assignments at 0x7fd84fa7cd90>

  File "/home/zhaolimin/YOLOX/yolox/models/yolo_head.py", line 452, in get_assignments
    gt_bboxes_per_image = gt_bboxes_per_image.cpu().float()
                          │                   └ <method 'cpu' of 'torch._C._TensorBase' objects>
                          └ <unprintable Tensor object>

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:312: operator(): block: [0,0,0], thread: [12,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:312: operator(): block: [0,0,0], thread: [26,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:312: operator(): block: [0,0,0], thread: [27,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.

**Comment by MangoloD** [comment]
检查下是否将yolox_voc_s里面的num_classes改成了你自己训练集的类别个数

**Comment by 18789447455** [comment]
> Please check exps/example/custom/yolox_l.py, set self.num_classe as your class num.

谢谢！问题解决了

**Comment by 18789447455** [comment]
> Please check exps/example/custom/yolox_l.py, set self.num_classe as your class num.
为什么改了类别数还出现这个问题

**Comment by Ranger-D** [comment]
Which weight did you use?

**Comment by 18789447455** [comment]
> Which weight did you use?

yolox_l

**Comment by Ranger-D** [comment]
Which format of data did you use? coco?

**Comment by 18789447455** [comment]
> Which format of data did you use? coco?
我用的visdrone2019，我加了transformer模块，训练到第五个epoch报的这个错

**Comment by Ranger-D** [comment]
> > Which format of data did you use? coco?
> > 我用的visdrone2019，我加了transformer模块，训练到第五个epoch报的这个

**Comment by Ranger-D** [comment]
> > Which format of data did you use? coco?
> > 我用的visdrone2019，我加了transformer模块，训练到第五个epoch报的这个错

I have know idea, because if we set up class number wrongly, the error would show out at epoch 1 and I don't carry out the same experiment. But I suggest that you can check out all configuration files about the experiment.

**Comment by 18789447455** [comment]
> > > Which format of data did you use? coco?
> > > 我用的visdrone2019，我加了transformer模块，训练到第五个epoch报的这个错
> 
> I have know idea, because if we set up class number wrongly, the error would show out at epoch 1 and I don't carry out the same experiment. But I suggest that you can check out all configuration files about the experiment.

想问下您配置文件在哪块，需要核对什么内容

**Comment by Ranger-D** [comment]
> > > > Which format of data did you use? coco?
> > > > 我用的visdrone2019，我加了transformer模块，训练到第五个epoch报的这个错
> > 
> > 
> > I have know idea, because if we set up class number wrongly, the error would show out at epoch 1 and I don't carry out the same experiment. But I suggest that you can check out all configuration files about the experiment.
> 
> 想问下您配置文件在哪块，需要核对什么内容

Excuse me, it's just my assumption, but I don't how to operate, so you'd better expect other developers. opps....

**Comment by 18789447455** [comment]
你在哪加的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月17日(周三) 下午2:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Megvii-BaseDetection/YOLOX] 请问这个问题应该怎么解决 (#738)




     
Which format of data did you use? coco?
 我用的visdrone2019，我加了transformer模块，训练到第五个epoch报的这个错
   
I have know idea, because if we set up class number wrongly, the error would show out at epoch 1 and I don't carry out the same experiment. But I suggest that you can check out all configuration files about the experiment.
  
想问下您配置文件在哪块，需要核对什么内容
  
Excuse me, it's just my assumption, but I don't how to operate, so you'd better expect other developers. opps....
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
