### ISSUE TITLE
CUDA kernel errors might be asynchronously reported  when using gpu as the device

### ISSUE THREAD

**Issue by GeLink9999** [Megvii-BaseDetection/YOLOX#87]
ython tools/demo.py image -n yolox-s -c /workspace/ShareData/YOLOX-main/exps/yolox_s.pth.tar --path assets/AIV.png --conf 0.3 --nms 0.65 --tsize 640 --save_result --device gpu

2021-07-22 21:45:17.149 | INFO     | __main__:main:220 - Args: Namespace(camid=0, ckpt='/workspace/ShareData/YOLOX-main/exps/yolox_s.pth.tar', conf=0.3, demo='image', device='gpu', exp_file=None, experiment_name='yolox_s', fp16=False, fuse=False, name='yolox-s', nms=0.65, path='assets/AIV.png', save_result=True, trt=False, tsize=640)
/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
2021-07-22 21:45:17.498 | INFO     | __main__:main:230 - Model Summary: Params: 8.97M, Gflops: 26.81
/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py:106: UserWarning:
GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the GeForce RTX 3090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
2021-07-22 21:45:19.713 | INFO     | __main__:main:241 - loading checkpoint
2021-07-22 21:45:19.800 | INFO     | __main__:main:245 - loaded checkpoint done.
Traceback (most recent call last):
  File "tools/demo.py", line 277, in <module>
    main(exp, args)
  File "tools/demo.py", line 268, in main
    image_demo(predictor, vis_folder, args.path, current_time, args.save_result)
  File "tools/demo.py", line 162, in image_demo
    outputs, img_info = predictor.inference(image_name)
  File "tools/demo.py", line 125, in inference
    outputs = self.model(img)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/ShareData/YOLOX-main/yolox/models/yolox.py", line 30, in forward
    fpn_outs = self.backbone(x)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/ShareData/YOLOX-main/yolox/models/yolo_pafpn.py", line 88, in forward
    out_features = self.backbone(input)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/ShareData/YOLOX-main/yolox/models/darknet.py", line 144, in forward
    x = self.stem(x)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/ShareData/YOLOX-main/yolox/models/network_blocks.py", line 172, in forward
    (patch_top_left, patch_bot_left, patch_top_right, patch_bot_right,), dim=1,
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by imneonizer** [comment]
It is the issue with your `GPU` and `PyTorch` installation see the above warning
````
GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
````

I checked the `demo.py` on GTX 1650 with below configurations and it works fine.
- NVIDIA-SMI 465.19.01
- Driver Version: 465.19.01
- CUDA Version: 11.3
- PyTorch: 1.8.1+cu111

**Comment by GeLink9999** [comment]
> It is the issue with your `GPU` and `PyTorch` installation see the above warning
> 
> ```
> GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
> ```
> 
> I checked the `demo.py` on GTX 1650 with below configurations and it works fine.
> 
> * NVIDIA-SMI 465.19.01
> * Driver Version: 465.19.01
> * CUDA Version: 11.3
> * PyTorch: 1.8.1+cu111

Thanks very much for your information. I will try it.
