### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by Petilia** [Megvii-BaseDetection/YOLOX#931]
I'm launching a model training
Then I see the messages:
![image](https://user-images.githubusercontent.com/94632457/142770298-224eaa58-69b8-4e39-b4b0-835f15d977c0.png)
Then I see errors
![image](https://user-images.githubusercontent.com/94632457/142770309-1230e1a1-42b4-4e5a-bbb6-0aa8fa1ffd12.png)
What could be the problem?

**Comment by FateScript** [comment]
It's an async problem, and this issue is always caused by illegal memory access . e.g. an tensor contains 4 number, but you access the 5th value.

**Comment by JCRONG96** [comment]
I also have this issue when I train yolox in win10. Have you solved it?

**Comment by mahdiabdollahpour** [comment]
I have the same issue. This is async. Have you debugged to see which line causes the error?

**Comment by song2park** [comment]
Same issue here. how can i fix this?

**Comment by mahdiabdollahpour** [comment]
> Same issue here. how can i fix this?

reduce the learning rate.

**Comment by marcus-neo** [comment]
Hi @song2park can I confirm that this issue can indeed be fixed by reducing the learning rate, like what @mahdiabdollahpour  has mentioned? Thanks so much!

**Comment by lawrencekiba** [comment]
> > Same issue here. how can i fix this?
> 
> reduce the learning rate.

this doesn't solve it from my end.

**Comment by zehranrgi** [comment]
Is there any solution to it?

**Comment by valentinBraeutigam** [comment]
A problem can be that the number of label ids you have is higher than the number you specified in the configuration of the network.
As described here: [https://stackoverflow.com/questions/58242415/how-to-fix-runtimeerror-cuda-error-device-side-assert-triggered-in-pytorch](https://stackoverflow.com/questions/58242415/how-to-fix-runtimeerror-cuda-error-device-side-assert-triggered-in-pytorch)
